# 1. Base image: ROS 2 Jazzy (based on Ubuntu 24.04 Noble)
FROM osrf/ros:jazzy-desktop

# 2. Install essential tools and dependencies
RUN apt-get update && apt-get install -y \
    wget \
    curl \
    lsb-release \
    gnupg \
    nano \
    gedit \
    sudo \
    libglx-mesa0 \
    libopengl0 \
    libglu1-mesa

# 3. Add the repository and key for Gazebo Harmonic correctly (using signed-by method)
RUN curl https://packages.osrfoundation.org/gazebo.gpg --output /usr/share/keyrings/pkgs-osrf-archive-keyring.gpg \
    && echo "deb [arch=amd64 signed-by=/usr/share/keyrings/pkgs-osrf-archive-keyring.gpg] http://packages.osrfoundation.org/gazebo/ubuntu-stable $(lsb_release -cs) main" > /etc/apt/sources.list.d/gazebo-stable.list

# 4. Install ROS 2 Gazebo bridge and Gazebo Harmonic
RUN apt-get update && apt-get install -y \
    python3-pip python3-colcon-common-extensions \
    ros-jazzy-slam-toolbox \
    ros-jazzy-nav2-map-server \
    ros-jazzy-ros-gz-bridge \
    ros-jazzy-ros-gz \
    gz-harmonic \
    ros-jazzy-joint-state-publisher \
    && rm -rf /var/lib/apt/lists/*

# 5. Install Visual Studio Code
RUN wget -qO- https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > packages.microsoft.gpg \
    && install -o root -g root -m 644 packages.microsoft.gpg /etc/apt/trusted.gpg.d/ \
    && sh -c 'echo "deb [arch=amd64] https://packages.microsoft.com/repos/code stable main" > /etc/apt/sources.list.d/vscode.list' \
    && apt-get update \
    && apt-get install -y code \
    && rm -rf /var/lib/apt/lists/* packages.microsoft.gpg

# 6. Set the working directory
WORKDIR /uc-miis-master-project-ws

# 7. Source the workspace automatically on container startup
RUN echo 'source /opt/ros/jazzy/setup.bash' >> ~/.bashrc && \
    echo 'source /uc-miis-master-project-ws/thesis_ws/install/setup.bash' >> ~/.bashrc

# 8. Set Git global config (optional)
RUN git config --global user.name "Name Surname" \
 && git config --global user.email "your@email.com"

# 9. Update .bashrc to source ROS 2 environment and define VSCode alias
RUN echo "source /opt/ros/jazzy/setup.bash" >> /root/.bashrc \
    && echo 'alias code="code --no-sandbox --user-data-dir=/vscode-user-data --extensions-dir=/vscode-extensions"' >> /root/.bashrc

# 10. Start a bash shell when the container launches
CMD ["bash"]
